version: '3'

services:
    db:
      image: mongo:latest
      container_name: ${PROJECT_NAME}-api-mongodb
      restart: always
      volumes:
        - db-data-prod:/data/db
        - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_DB_USER: ${MONGO_DB_USER}
        MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
        MONGO_DB_NAME: ${MONGO_DB_NAME}
      # ports:
      #   - "27017:27017"
      command: [--auth]

    ghost.service:
      build:
        context: ./
        dockerfile: Dockerfile
      depends_on:
        - db
      container_name: ${PROJECT_NAME}-api-server
      restart: always
      environment:
        MONGO_URI: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@db:27017/${MONGO_DB_NAME}
        NODE_ENV: ${NODE_ENV}
        REACT_APP_API_URL_API_URL: ${API_URL}
      ports:
        - "${PORT}:3000"
 
volumes:
  db-data-prod: