version: '3'

services:
    db_dev:
      image: mongo:latest
      container_name: ${PROJECT_NAME}-api-mongodb-dev
      restart: always
      volumes:
        - db-data-dev:/data/db
        - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_DB_USER: ${MONGO_DB_USER}
        MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
        MONGO_DB_NAME: ${MONGO_DB_NAME}
      ports:
        - "27017:27017"
      command: [--auth]
    
    db_client_dev:
      image: mongo-express:latest
      depends_on:
        - db_dev
      container_name: ${PROJECT_NAME}-api-mongoclient
      restart: always
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USER}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
        ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@db_dev:27017/${MONGO_DB_NAME}
      ports:
      - "8081:8081"

volumes:
  db-data-dev: